config/routes.rb
W1Dating::Application.routes.draw do
  resources :providers

  root 'home#index'
  get 'about' => 'home#about', as: :about
  get 'compare' => 'home#compare', as: :compare

end

app/models/provider.rb
class Provider < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @providers = Provider.all
  end

  def compare
    @providers = Provider.all
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render action: 'show', status: :created, location: @provider }
      else
        format.html { render action: 'new' }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :site_type, :users, :rating, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/home/about.haml
- @active = "about"
.container
  %h1 About Smilingly
  %p So what are we all about here at Smilingly? Well it's simple: We want to have fun dating.

  %h1 Advertise on Smilingly
  %p Want to advertise on this website? Sure thing, get in touch with us at...

app/views/home/compare.haml
.container
  %h2 Compare Dating sites
  .table-responsive
    %table.table.table-hover
      %tr
        %th Website
        %th Type
        %th Users
        %th Rating
        %th Visit
      - for provider in @providers
        %tr
          %td= provider.name
          %td= provider.site_type
          %td= provider.users
          %td= provider.rating
          %td= link_to "Visit", provider.url, class: "btn btn-primary"

app/views/home/index.haml
.container
  .jumbotron
    %h1 Love, smilingly.
    %p It doesn't matter who you are, or where you come from. We all deserve to find that special connection with someone. So that we can live life Smilingly.
    %p
      %a.btn.btn-lg.btn-primary{href: "../../components/#navbar", role: "button"} Sign Up

.container
  .row
    .col-sm-6.col-md-3
      .thumbnail
        = image_tag "http://placehold.it/300x200", alt: "Profile!"
        .caption
          %h3 Profile!
          %p "I never know what to put in these things! Hahah, what am I like?!"
          %p
            %a.btn.btn-primary Contact
            %a.btn.btn-default Ping
    .col-sm-6.col-md-3
      .thumbnail
        = image_tag "http://placehold.it/300x200", alt: "Profile!"
        .caption
          %h3 Profile!
          %p "I never know what to put in these things! Hahah, what am I like?!"
          %p
            %a.btn.btn-primary Contact
            %a.btn.btn-default Ping
    .col-sm-6.col-md-3
      .thumbnail
        = image_tag "http://placehold.it/300x200", alt: "Profile!"
        .caption
          %h3 Profile!
          %p "I never know what to put in these things! Hahah, what am I like?!"
          %p
            %a.btn.btn-primary Contact
            %a.btn.btn-default Ping
    .col-sm-6.col-md-3
      .thumbnail
        = image_tag "http://placehold.it/300x200", alt: "Profile!"
        .caption
          %h3 Profile!
          %p "I never know what to put in these things! Hahah, what am I like?!"
          %p
            %a.btn.btn-primary Contact
            %a.btn.btn-default Ping

app/views/layouts/_footer.haml
%footer.footer
  .container
    &copy; Stevan 2014

app/views/layouts/application.haml
!!!
%html
  %head
    %title Date Smilingly
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      = render "shared/header", active: @active || "home"
      = render "shared/notices"
    = yield
    = render "layouts/footer"

app/views/providers/_form.html.haml
= form_for @provider do |f|
  - if @provider.errors.any?
    #error_explanation
      %h2= "#{pluralize(@provider.errors.count, "error")} prohibited this provider from being saved:"
      %ul
        - @provider.errors.full_messages.each do |msg|
          %li= msg

  .actions
    .form-group
      %label{for: ""} Site name
      = f.text_field :name, class: "form-control", placeholder: "Name"
    .form-group
      %label{for: ""} Type
      = f.text_field :site_type, class: "form-control", placeholder: "Casual"
    .form-group
      %label{for: ""} Rating
      = f.text_field :rating, class: "form-control", placeholder: "99"
    .form-group
      %label{for: ""} Users notes
      = f.text_field :users, class: "form-control", placeholder: "Lots of users"
    .form-group
      %label{for: ""} URL
      = f.text_field :url, class: "form-control", placeholder: "http://"
    = f.submit 'Save', class: "btn btn-default"

app/views/providers/edit.html.haml
%h1 Editing provider

= render 'form'

= link_to 'Show', @provider
\|
= link_to 'Back', providers_path

app/views/providers/index.html.haml
%h1 Listing providers

%table
  %tr
    %th
    %th
    %th

  - @providers.each do |provider|
    %tr
      %td= link_to 'Show', provider
      %td= link_to 'Edit', edit_provider_path(provider)
      %td= link_to 'Destroy', provider, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Provider', new_provider_path

app/views/providers/new.html.haml
.container
  %h1 New provider

  = render 'form'

  = link_to 'Back', providers_path

app/views/providers/show.html.haml
.container
  %p#notice= notice
  .table-responsive
    %table.table
      %tr
        %th Site Name
        %td= @provider.name
      %tr
        %th Site Type
        %td= @provider.site_type
      %tr
        %th Users notes
        %td= @provider.users
      %tr
        %th Rating
        %td= @provider.rating
      %tr
        %th Affiliate URL
        %td= @provider.url
  = link_to 'Edit', edit_provider_path(@provider)
  \|
  = link_to 'Back', providers_path

app/views/shared/_header.haml
%header.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "#{root_url}"} Smilingly.com
    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li{class: "#{active == "home" ? 'active' : ''}"}
          %a{href: "#{root_path}"} Home
      %ul.nav.navbar-nav.navbar-right
        %li{class: "#{active == "about" ? 'active' : ''}"}
          %a{href: "#{about_path}"} About
        %li
          %a{href: "#contact"} Contact

app/views/shared/_notices.haml
- flash.each do |name, msg|
  .alert.alert-dismissable{class: "alert-#{name.to_s}"}
    %button{type: "button", class: "close", data: {dismiss: "alert"}, aria: {hidden: "true"}} &times;
    = msg